
server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
      routes:
        - id: estore-service
          uri: https://estore-middleware.l1ka5j7kal692.ap-south-1.cs.amazonlightsail.com
          predicates:
            - Path=/e-store/**

        - id: http://13.234.216.10
          uri: http://13.234.216.10
          predicates:
            - Path=/**

